[versions]
editor = "0.23.4"
androidx-navigation = "2.7.7"

junit = "4.13.2"
androidx-junit = "1.1.5"
espresso-core = "3.5.1"
termux = "0.118.1"
p7zip = "v1.7.2"

[libraries]

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.7.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-core = { module = "androidx.core:core", version = "1.12.0" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-desugar = { module = "com.android.tools:desugar_jdk_libs", version ="2.0.4" }
androidx-fragment_ktx = { module = "androidx.fragment:fragment-ktx", version = "1.6.2" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-nav-dynamic_features = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidx-navigation" }
androidx-webkit = { module = "androidx.webkit:webkit", version = "1.8.0" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# Google
google-guava = { module = "com.google.guava:guava", version = "32.1.3-jre" }
google-gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
google-material = { module = "com.google.android.material:material", version = "1.10.0" }

# Common
common-editor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "editor" }
common-eventbus = { module = "org.greenrobot:eventbus", version = "3.3.1" }
common-jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.2.700" }
common-jsoup = { module = "org.jsoup:jsoup", version = "1.16.2" }
common-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.12" }
common-utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
common-android-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.7.3" }
common-pf4j = { module = "org.pf4j:pf4j", version = "3.10.0" }
common-kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.1" }
common-junit = { group = "junit", name = "junit", version.ref = "junit" }
common-p7zip = { module = "com.github.hzy3774:AndroidP7zip", version.ref = "p7zip" }

# Termux
terminal-view = { module = "com.github.termux.termux-app:terminal-view", version.ref = "termux" }
terminal-emulator = { module = "com.github.termux.termux-app:terminal-emulator", version.ref = "termux" }

[plugins]
android-application = { id = "com.android.application", version = "8.1.1" }
android-library = { id = "com.android.library", version = "8.1.1" }
kotlin = { id = "org.jetbrains.kotlin.android", version = "1.9.10" }