[versions]
android-tree-sitter = "4.3.1"
androidsvg = "1.4"
browser = "1.8.0"
bsh = "3.0.0-SNAPSHOT"
compose-markdown = "0.5.4"
editor = "0.23.5"
androidx-navigation = "2.8.5"
generativeai = "0.9.0"
konfetti-compose = "2.0.4"
compose-preference-library = "1.1.1"
kotlinx-coroutines = "1.10.1"
kotlinx-serialization-json = "1.7.3"
material-icons-extended = "1.7.6"
nanohttpd = "2.3.1"
navigation-compose = "2.8.6"
okhttp = "4.12.0"
lsp4j = "0.23.1"
jgit = "7.0.0.202409031743-r"
retrofit = "2.11.0"
security-crypto = "1.1.0-alpha06"
termux = "0.118.1"
p7zip = "v1.7.2"
lifecycle-runtime = "2.8.7"
activity-compose = "1.10.1"
kotlin = "2.2.10"
compose-bom = "2025.02.00"
termux-shared = "0.118.1"
datastore = "1.1.1"
accompanist = "0.36.0"
coil = "3.0.3"
aboutLibraries = "11.6.3"
webkit = "1.12.1"
junit = "4.13.2"
junit-version = "1.2.1"
espresso-core = "3.6.1"
orbit = "0.39.0"

[libraries]

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-core = { module = "androidx.core:core", version = "1.15.0" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.15.0" }
androidx-desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }
androidx-fragment_ktx = { module = "androidx.fragment:fragment-ktx", version = "1.8.6" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-nav-dynamic_features = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidx-navigation" }
androidx-datastore-prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

# Google
google-generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
google-guava = { module = "com.google.guava:guava", version = "33.3.1-jre" }
google-gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
google-material = { module = "com.google.android.material:material", version = "1.12.0" }
google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# Common
common-editor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "editor" }
common-editor-lsp = { module = "io.github.Rosemoe.sora-editor:editor-lsp", version.ref = "editor" }
common-editor-textmate = { module = "io.github.Rosemoe.sora-editor:language-textmate", version.ref = "editor" }
common-editor-treesitter = { module = "io.github.Rosemoe.sora-editor:language-treesitter", version.ref = "editor" }
common-eventbus = { module = "org.greenrobot:eventbus", version = "3.3.1" }
common-jsoup = { module = "org.jsoup:jsoup", version = "1.18.1" }
common-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.13" }
common-utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
common-p7zip = { module = "com.github.hzy3774:AndroidP7zip", version.ref = "p7zip" }
common-terminal-view = { module = "com.github.termux.termux-app:terminal-view", version.ref = "termux" }
common-terminal-emulator = { module = "com.github.termux.termux-app:terminal-emulator", version.ref = "termux" }

konfetti-compose = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfetti-compose" }
compose-preference-library = { module = "me.zhanghai.compose.preference:library", version.ref = "compose-preference-library" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "compose-markdown" }
org-eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
org-eclipse-lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
org-eclipse-lsp4j-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version.ref = "lsp4j" }
bsh = { module = "org.beanshell:bsh", version.ref = "bsh" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }

android-tree-sitter = { module = "com.itsaky.androidide.treesitter:android-tree-sitter", version.ref = "android-tree-sitter" }
tree-sitter-java = { module = "com.itsaky.androidide.treesitter:tree-sitter-java", version.ref = "android-tree-sitter" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
termux-app-termux-shared = { module = "com.github.termux.termux-app:termux-shared", version.ref = "termux-shared" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

orbit-ui = { module = "kiwi.orbit.compose:ui", version.ref = "orbit" }
orbit-icons = { module = "kiwi.orbit.compose:icons", version.ref = "orbit" }

[plugins]
android-application = { id = "com.android.application", version = "8.8.2" }
android-library = { id = "com.android.library", version = "8.8.2" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
